# Generated by Django 6.0.6 on 2026-06-11 05:39

import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=128, verbose_name='Название мероприятия')),
                ('event_date', models.DateField(verbose_name='Дата меоприятия')),
                ('event_time', models.TimeField(verbose_name='Время начала мероприятия')),
                ('event_location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('event_description', models.TextField(verbose_name='Описание для мероприятия')),
                ('event_photo', models.ImageField(upload_to='medias', verbose_name='Фото ивента')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
