# Generated by Django 6.0.6 on 2026-06-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_brandlogo_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandlogo',
            name='brand_name',
            field=models.CharField(default='BrandName', max_length=128, verbose_name='Имя бренда'),
        ),
    ]
