# Generated by Django 6.0.6 on 2026-06-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_brandlogo_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.TextField(verbose_name='Вставьте код с локацией'),
        ),
    ]
