# Generated by Django 6.0.6 on 2026-06-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_event_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.URLField(verbose_name='Вставьте ссылку'),
        ),
    ]
