# Generated by Django 6.0.6 on 2026-06-12 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_event_event_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=32, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=32, verbose_name='Название тренинга')),
                ('game_sub_name', models.TextField(verbose_name='Подзаголовок для тренинга')),
                ('game_desc', models.TextField(verbose_name='Описание тренинга')),
                ('game_skills', models.TextField(verbose_name='Получаемые навыки')),
                ('game_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gamescategory')),
            ],
            options={
                'verbose_name': 'Тренинг',
                'verbose_name_plural': 'Тренинги',
            },
        ),
    ]
