# Generated by Django 6.0.6 on 2026-06-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_gamescategory_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='game_photo1',
            field=models.ImageField(default='', upload_to='medias', verbose_name='Фото тренинга'),
        ),
        migrations.AddField(
            model_name='games',
            name='game_photo2',
            field=models.ImageField(default='', upload_to='medias', verbose_name='Фото тренинга'),
        ),
        migrations.AddField(
            model_name='games',
            name='game_photo3',
            field=models.ImageField(default='', upload_to='medias', verbose_name='Фото тренинга'),
        ),
        migrations.AddField(
            model_name='games',
            name='game_photo4',
            field=models.ImageField(default='', upload_to='medias', verbose_name='Фото тренинга'),
        ),
        migrations.AddField(
            model_name='games',
            name='game_photo5',
            field=models.ImageField(default='', upload_to='medias', verbose_name='Фото тренинга'),
        ),
    ]
