# Generated by Django 6.0.6 on 2026-06-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_games_game_photo1_games_game_photo2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_photo',
        ),
    ]
