# Generated by Django 6.0.6 on 2026-06-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_event_event_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_description',
        ),
    ]
