# Generated by Django 6.0.6 on 2026-06-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_event_event_place_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_place_name',
            field=models.CharField(max_length=64, verbose_name='Название места'),
        ),
    ]
