# Generated by Django 6.0.6 on 2026-06-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_event_event_place_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_time',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.TextField(verbose_name='Дата меоприятия'),
        ),
    ]
