# Generated by Django 6.0.6 on 2026-06-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_event_event_time_alter_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_place_name',
            field=models.CharField(default='', max_length=64, verbose_name='Название места'),
        ),
    ]
