# Generated by Django 6.0.6 on 2026-06-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_event_event_place_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_age_min',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_amount',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_max_age',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_place_name',
        ),
    ]
