# Generated by Django 6.0.6 on 2026-06-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_event_event_age_min_remove_event_event_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_age_min',
            field=models.CharField(default=9, max_length=8, verbose_name='Минимальный возраст участника'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_amount',
            field=models.CharField(default='0/9', max_length=8, verbose_name='Свободно мест'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_max_age',
            field=models.CharField(default=99, max_length=8, verbose_name='Минимальный возраст участника'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_place_name',
            field=models.CharField(default='', max_length=64, verbose_name='Название места'),
        ),
    ]
