# Generated by Django 6.0.6 on 2026-06-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_event_event_age_min_event_event_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_age_min',
            field=models.CharField(max_length=8, verbose_name='Минимальный возраст участника'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_max_age',
            field=models.CharField(max_length=8, verbose_name='Минимальный возраст участника'),
        ),
    ]
