# Generated by Django 6.0.6 on 2026-06-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_event_event_age_min_alter_event_event_max_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_max_age',
            new_name='event_age_max',
        ),
    ]
