# Generated by Django 6.0.6 on 2026-06-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_event_max_age_event_event_age_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='game_time',
            field=models.TextField(default='4', verbose_name='Сколько идет игра? (от-до)'),
        ),
        migrations.AlterField(
            model_name='brandlogo',
            name='brand_image',
            field=models.ImageField(upload_to='media', verbose_name='Лого бренда'),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_photo1',
            field=models.ImageField(default='', upload_to='media', verbose_name='Фото тренинга'),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_photo2',
            field=models.ImageField(default='', upload_to='media', verbose_name='Фото тренинга'),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_photo3',
            field=models.ImageField(default='', upload_to='media', verbose_name='Фото тренинга'),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_photo4',
            field=models.ImageField(default='', upload_to='media', verbose_name='Фото тренинга'),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_photo5',
            field=models.ImageField(default='', upload_to='media', verbose_name='Фото тренинга'),
        ),
        migrations.AlterField(
            model_name='team',
            name='worker_image',
            field=models.ImageField(upload_to='media', verbose_name='Фото сотрудника'),
        ),
    ]
