# Generated by Django 6.0.6 on 2026-06-30 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_games_game_time_alter_brandlogo_brand_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='game_photo1',
        ),
        migrations.RemoveField(
            model_name='games',
            name='game_photo2',
        ),
        migrations.RemoveField(
            model_name='games',
            name='game_photo3',
        ),
        migrations.RemoveField(
            model_name='games',
            name='game_photo4',
        ),
        migrations.RemoveField(
            model_name='games',
            name='game_photo5',
        ),
        migrations.CreateModel(
            name='Game_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_text', models.TextField(default='Фото')),
                ('game_photo', models.ImageField(upload_to='media', verbose_name='Фото мероприятия')),
                ('game_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.games')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотки',
            },
        ),
    ]
