# Generated by Django 6.0.6 on 2026-07-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_games_game_photo1_remove_games_game_photo2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='game_players',
            field=models.TextField(default='до 9 чел', verbose_name='Кол-во участников'),
        ),
    ]
